--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3 (Debian 16.3-1.pgdg120+1)
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: address; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.address (
    id_address bigint NOT NULL,
    country character varying(255),
    details character varying(255),
    municipality character varying(255),
    province character varying(255)
);


ALTER TABLE public.address OWNER TO postgres;

--
-- Name: address_id_address_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.address ALTER COLUMN id_address ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.address_id_address_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hotels; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.hotels (
    id_hotel bigint NOT NULL,
    category integer NOT NULL,
    address_id bigint,
    trip_id bigint
);


ALTER TABLE public.hotels OWNER TO postgres;

--
-- Name: hotels_id_hotel_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.hotels ALTER COLUMN id_hotel ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hotels_id_hotel_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: houses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.houses (
    id_house bigint NOT NULL,
    color character varying(255),
    address_id bigint
);


ALTER TABLE public.houses OWNER TO postgres;

--
-- Name: houses_id_house_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.houses ALTER COLUMN id_house ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.houses_id_house_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: people; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.people (
    id_person bigint NOT NULL,
    age integer NOT NULL,
    ci character varying(255) NOT NULL,
    name character varying(255)
);


ALTER TABLE public.people OWNER TO postgres;

--
-- Name: people_id_person_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.people ALTER COLUMN id_person ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.people_id_person_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: person_has_address; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.person_has_address (
    people_idperson bigint NOT NULL,
    address_idaddress bigint NOT NULL
);


ALTER TABLE public.person_has_address OWNER TO postgres;

--
-- Name: person_has_house; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.person_has_house (
    people_idperson bigint NOT NULL,
    house_idhouse bigint NOT NULL
);


ALTER TABLE public.person_has_house OWNER TO postgres;

--
-- Name: person_has_trip; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.person_has_trip (
    people_idperson bigint NOT NULL,
    trip_idtrip bigint NOT NULL
);


ALTER TABLE public.person_has_trip OWNER TO postgres;

--
-- Name: trips; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trips (
    id_trip bigint NOT NULL,
    date timestamp(6) without time zone,
    id_hotel integer NOT NULL,
    address_id bigint
);


ALTER TABLE public.trips OWNER TO postgres;

--
-- Name: trips_id_trip_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.trips ALTER COLUMN id_trip ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trips_id_trip_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: address; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.address (id_address, country, details, municipality, province) FROM stdin;
1	Japan	52b88ed8-a588-4839-858f-cb18c8f4d3b3	Toyohama	\N
2	China	a624e4f5-2149-4a08-bbaf-9a6a21d04f28	Shuangquan	\N
3	Cuba	07990189-31cd-4eca-97ba-5c93b4586460	Habana	\N
4	Indonesia	b0f79627-fb40-4713-8cdf-1e94c2e0b9d6	Oenunu	\N
5	Brazil	8cf25ba5-e0b9-4783-915c-b81641398067	Satuba	\N
6	Cuba	Undia en el cotorro se puso bueno	Cotorro	Habana
7	Cuba	91736ed4-8db2-4de3-883f-6777f50c7987	San Juan Bautista	Pinar del rio
8	Afghanistan	06c9d95a-6232-4f08-9ded-3f310d6b9a64	Gardēz	\N
9	China	14bec7cf-2704-403a-849e-b879be4174ce	Aimin	\N
10	Cuba	3900b208-d112-4ca3-baf6-2a0dfda96137	Habana	Cotorro
11	Ukraine	5380d25b-83ff-47b1-a887-4774a420314d	Pavlivka	\N
12	Czech Republic	1979eb94-b90f-425c-92b5-c29e99b93c0f	Krupka	\N
13	Belize	874ecca8-225b-4d92-81a8-5641f4acc39e	Shangyi	\N
14	Honduras	fb8b2584-2be6-44a9-b2b4-2a5e6ffffa86	Peña Blanca	\N
15	Moldavia	be7e422f-c6b6-4541-80a7-5b498c1691c0	Sheshan	\N
16	Syria	a8c5aa07-2d35-4d89-82e2-e5192b1eb7bd	Ḩammām Wāşil	\N
17	Cuba	0b4e1115-ae87-4bc1-9d56-7589fdef6658	Cinfuentes	Cinfuegos
18	Cambodia	2b15045c-dc89-4f59-91e7-d269ce37179a	Kampong Cham	\N
19	Marchall	0c17440e-bea3-482d-9197-2de0ffad7e8e	Jōetsu	\N
20	Israel	8bd73041-b573-4d20-ab70-aa6a1853c4ac	Chiba	\N
21	Finland	5e4521e6-be02-435a-98a8-e826f649280a	Joutsa	\N
22	France	fe4a4d38-4569-48e3-b095-93482ccb34dc	Poissy	Île-de-France
23	Slovenia	916784ba-b17e-4edd-a00b-cbc5421afc44	Rogoza	\N
24	Paises bajos	8e7f34c0-e53b-40de-b07d-b91d0b42ccd0	Chimen	\N
25	Philippines	39428731-e967-42b8-9e5f-ec6f107a37fc	Calabugao	\N
26	Greece	3783fcbc-fce4-4419-a3a4-84b6c5638c4f	Makrychóri	\N
27	Thailand	01b91001-0972-4e28-ae6d-205d5dcc34e3	Chon Daen	\N
28	Colombia	81fcbc7a-db6b-449d-9c68-7e61386c1628	Xihe	\N
29	Mexico	caaf77a0-8e67-462d-9ed3-52d0ab981c3e	Pueblo Nuevo	\N
30	Kenya	bf3dd524-6147-48c5-9022-3cfe525fc938	Athi River	\N
31	India	5d6aa1e1-5498-481f-a145-b620594e2873	Wonocoyo Utara	\N
32	Portugal	d319a47a-8673-42bb-955e-b1ee784cdf07	Nossa Senhora de Machede	Évora
33	Palaus	c8cf4244-0e52-49d0-be7a-71c52e680e31	Kubangkondanglapangan	\N
34	Austria	1d5ad14a-3cdf-4f73-9ccf-e2a9ebe11934	Batukuta	\N
35	AUSTRLIA	d555817e-3a14-45a9-9dc4-4f50ea24cbc2	Daigo	\N
36	New Zealand	9ad07f2b-69b3-4189-ac83-b3d091c69ce2	Whakatane	\N
37	Hungary	b51f03e4-dbf7-4212-91dc-00a3c61df2df	Debrecen	Hajdú-Bihar
38	Jamaica	a1483f71-62b0-42d0-818e-2b30ee7d499e	Stony Hill	\N
39	Mongolia	fdcb60b9-cd28-469b-a06b-ef1176479cb4	Shulan	\N
40	Korea	f3f2a368-d2dc-46de-a8c5-52c854ae8b6c	Tungoo	\N
41	Ucrania	2c45106f-1d7f-473c-a098-457e99ff11fd	Xinchang	\N
42	Martell	5cd74491-a718-4f0c-93a3-0efa01be6b41	Sukamaju	\N
43	Switzerland	5378c21f-fb55-4d2b-8b53-a4d6c5f96d8f	Zürich	Kanton Zürich
44	Thailand	938f6565-e7f9-462c-9908-60320a2f16b1	Aranyaprathet	\N
45	Russia	6fe0314c-88f6-409a-9b23-17239003ec62	Lyubim	\N
46	Congo	dda40905-fa38-4505-b65e-9879f9aebdac	Bulungu	\N
47	Russia	3e6db245-d2d4-40bf-8de0-faf04f37a84e	Yessentuki	\N
48	Brazil	576d8fdc-1723-458c-8cc4-59326d7d9235	Gravataí	\N
49	Morocco	03f1a12c-9ed0-4cb4-925f-ee6d9db6f92b	Tazemmourt	\N
50	South Africa	260c762f-2350-4f23-b1da-c827e0453cbc	Maclear	\N
\.


--
-- Data for Name: hotels; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.hotels (id_hotel, category, address_id, trip_id) FROM stdin;
1	5	1	5
2	3	2	1
3	5	3	10
4	2	4	3
5	5	5	6
6	4	6	9
7	5	7	4
8	3	8	7
9	3	9	8
10	5	10	2
\.


--
-- Data for Name: houses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.houses (id_house, color, address_id) FROM stdin;
1	Azul	1
2	Pink	3
3	Turquoise	4
4	Azul	5
5	Crimson	6
6	Turquoise	2
7	Maroon	7
8	Azul	9
9	Turquoise	8
10	Indigo	10
\.


--
-- Data for Name: people; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.people (id_person, age, ci, name) FROM stdin;
1	11	5093002410	Arlyn Joberne
2	9	8366293742	Emogene D'Onisi
3	71	7316044977	Fleurette Roddick
4	38	8823631874	Perla Cunliffe
5	49	2663071455	Inez Wadeson
6	106	1024568970	Howie Cabrara
7	120	6707329316	Danie Assender
8	24	9229581240	Wandis Cawkwell
9	117	9515479711	Daniel Dukesbury
10	49	5601511934	Alyce Kleinmann
11	97	3599820821	Lynn Barszczewski
12	12	8832576627	Constantine Piggott
13	14	9686624066	Fletcher Higford
14	112	2143669860	Jillana Croshaw
\.


--
-- Data for Name: person_has_address; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.person_has_address (people_idperson, address_idaddress) FROM stdin;
1	6
2	4
3	7
1	10
8	5
7	4
9	10
10	2
4	3
3	2
\.


--
-- Data for Name: person_has_house; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.person_has_house (people_idperson, house_idhouse) FROM stdin;
1	1
2	10
3	9
10	3
5	7
4	6
8	2
3	5
5	5
9	10
\.


--
-- Data for Name: person_has_trip; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.person_has_trip (people_idperson, trip_idtrip) FROM stdin;
4	4
5	10
1	2
2	2
3	2
2	3
4	8
8	3
7	4
5	6
\.


--
-- Data for Name: trips; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.trips (id_trip, date, id_hotel, address_id) FROM stdin;
1	2023-03-27 00:00:00	6	1
2	2024-03-20 00:00:00	9	4
3	2024-03-18 00:00:00	8	3
4	2022-12-08 00:00:00	5	2
5	2023-07-23 00:00:00	2	5
6	2023-07-18 00:00:00	3	6
7	2023-03-05 00:00:00	1	7
8	2022-09-05 00:00:00	6	8
10	2022-12-24 00:00:00	6	9
9	2022-12-28 00:00:00	7	10
\.


--
-- Name: address_id_address_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.address_id_address_seq', 1, false);


--
-- Name: hotels_id_hotel_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.hotels_id_hotel_seq', 1, false);


--
-- Name: houses_id_house_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.houses_id_house_seq', 1, false);


--
-- Name: people_id_person_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.people_id_person_seq', 1, false);


--
-- Name: trips_id_trip_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.trips_id_trip_seq', 1, false);


--
-- Name: address address_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.address
    ADD CONSTRAINT address_pkey PRIMARY KEY (id_address);


--
-- Name: hotels hotels_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hotels
    ADD CONSTRAINT hotels_pkey PRIMARY KEY (id_hotel);


--
-- Name: houses houses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.houses
    ADD CONSTRAINT houses_pkey PRIMARY KEY (id_house);


--
-- Name: people people_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.people
    ADD CONSTRAINT people_pkey PRIMARY KEY (id_person);


--
-- Name: trips trips_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT trips_pkey PRIMARY KEY (id_trip);


--
-- Name: trips uk3gd3esngoam5itm1nxuktnay5; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT uk3gd3esngoam5itm1nxuktnay5 UNIQUE (address_id);


--
-- Name: people uk5sbiojmn7i539erqdjwkw2led; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.people
    ADD CONSTRAINT uk5sbiojmn7i539erqdjwkw2led UNIQUE (ci);


--
-- Name: houses ukfx43gwqyfq0gtqt6238ooym9m; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.houses
    ADD CONSTRAINT ukfx43gwqyfq0gtqt6238ooym9m UNIQUE (address_id);


--
-- Name: hotels uki5j8pjj7gttelyrhsbomgdmrx; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hotels
    ADD CONSTRAINT uki5j8pjj7gttelyrhsbomgdmrx UNIQUE (trip_id);


--
-- Name: hotels ukwho36q9mjwkmu27v3xycfjo9; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hotels
    ADD CONSTRAINT ukwho36q9mjwkmu27v3xycfjo9 UNIQUE (address_id);


--
-- Name: person_has_trip fk235ljcp8hw3rwgbmseef47h5v; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.person_has_trip
    ADD CONSTRAINT fk235ljcp8hw3rwgbmseef47h5v FOREIGN KEY (people_idperson) REFERENCES public.people(id_person);


--
-- Name: person_has_address fk3o5gwujjvm1v7u925qtxqad47; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.person_has_address
    ADD CONSTRAINT fk3o5gwujjvm1v7u925qtxqad47 FOREIGN KEY (people_idperson) REFERENCES public.people(id_person);


--
-- Name: hotels fk8bchp4752uk853vryv2o3oxgx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hotels
    ADD CONSTRAINT fk8bchp4752uk853vryv2o3oxgx FOREIGN KEY (trip_id) REFERENCES public.trips(id_trip);


--
-- Name: trips fkabgc8iargek7mmwjqv1ni90k2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT fkabgc8iargek7mmwjqv1ni90k2 FOREIGN KEY (address_id) REFERENCES public.address(id_address);


--
-- Name: person_has_trip fke9q2cdm7hdmnkfct9jriy6tes; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.person_has_trip
    ADD CONSTRAINT fke9q2cdm7hdmnkfct9jriy6tes FOREIGN KEY (trip_idtrip) REFERENCES public.trips(id_trip);


--
-- Name: person_has_house fker24on16f8gc23c8wytlh4aed; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.person_has_house
    ADD CONSTRAINT fker24on16f8gc23c8wytlh4aed FOREIGN KEY (house_idhouse) REFERENCES public.houses(id_house);


--
-- Name: houses fkj9iv4jfwdbrkj0ldu04jkis4e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.houses
    ADD CONSTRAINT fkj9iv4jfwdbrkj0ldu04jkis4e FOREIGN KEY (address_id) REFERENCES public.address(id_address);


--
-- Name: person_has_house fkq4cxyw4t2n6c75oeojc8h7de1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.person_has_house
    ADD CONSTRAINT fkq4cxyw4t2n6c75oeojc8h7de1 FOREIGN KEY (people_idperson) REFERENCES public.people(id_person);


--
-- Name: hotels fkqi7twk71v7d7fgtm1w09c9eri; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hotels
    ADD CONSTRAINT fkqi7twk71v7d7fgtm1w09c9eri FOREIGN KEY (address_id) REFERENCES public.address(id_address);


--
-- Name: person_has_address fksk6yg3oi5kqxxsfemu24elh89; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.person_has_address
    ADD CONSTRAINT fksk6yg3oi5kqxxsfemu24elh89 FOREIGN KEY (address_idaddress) REFERENCES public.address(id_address);


--
-- PostgreSQL database dump complete
--

